### ISSUE TITLE
Error when run on Kovan

### ISSUE THREAD

**Issue by duong1521991** [dekz/0x-v2-beta-starter#1]
It works fine on ganache but error when runs on Kovan
<img width="988" alt="screen shot 2018-07-04 at 2 17 16 pm" src="https://user-images.githubusercontent.com/6903264/42262278-058debaa-7f95-11e8-8174-96cbd8d0b23a.png">

**Comment by dekz** [comment]
hey @duong1521991 this is using Infura to talk to Kovan. It seems like a network issue. Are you able to retry and see if the problem persists?

There's also a debug file in there which does some INFURA reads:
```
node lib/scenarios/debug.js
```

**Comment by duong1521991** [comment]
@dekz  Hi, this problem always occur.
I'm also taking to Kovan using Infura with my registered api key:
<img width="998" alt="screen_shot_2018-07-04_at_2_43_37_pm" src="https://user-images.githubusercontent.com/6903264/42263665-e624f566-7f98-11e8-9570-0f8a722d4b40.png">

And this is the result after running debug file

<img width="882" alt="screen shot 2018-07-04 at 2 43 00 pm" src="https://user-images.githubusercontent.com/6903264/42263744-1e8b43e2-7f99-11e8-8ede-19defe3ec520.png">

**Comment by dekz** [comment]
I added my api key and was able to successfully run the scenario on Kovan just now.

Can you try pinging the Kovan API directly?
```
curl -X POST --data '{"jsonrpc":"2.0","method":"eth_getBlockByNumber","params":["0x61a80", true],"id":1}' -H "Content-Type: application/json" https://kovan.infura.io/
```

**Comment by duong1521991** [comment]
@dekz Hi, It looks like that is my office's network problem. It worked perfectly at home. Thanks a lot for your answer.

<img width="909" alt="screen shot 2018-07-04 at 4 17 04 pm" src="https://user-images.githubusercontent.com/6903264/42268526-f1b33a0c-7fa5-11e8-818b-28c9bf2afe43.png">
